packages:
  - '*'
  - '**'

catalogs:
  vite-plugins:
    '@babel/parser': ^7.27.0
    '@babel/traverse': ^7.28.5
    '@babel/types': ^7.28.5
    '@parse5/tools': ^0.5.0
    '@types/babel__traverse': ^7.20.7
    '@types/fs-extra': ^11.0.4
    '@types/node': ^25.0.3
    deepmerge-ts: ^7.1.5
    fs-extra: ^11.3.0
    globby: ^14.1.0
    lightningcss: ^1.29.3
    lit: ^3.3.0
    magic-string: ^0.30.17
    oxc-walker: ^0.6.0
    parse5: ^7.2.1
    rollup: ^4.40.0
    sass: ^1.86.3
    typedoc: ^0.28.15
    typedoc-github-theme: ^0.3.0
    typescript: ^5.9.2
    vite: ^7.3.0
    vitest: ^4.0.16

onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild

pnpmfile: ../.pnpmfile.cjs
