name: Deploy Documentation to GitHub Pages using typedoc

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  deploy-docs:
    uses: arcmantle/github-workflows/.github/workflows/deploy-typedoc.yml@main
    with:
      build-dependencies: '@arcmantle/tsconfig'
