name: Deploy Documentation to GitHub Pages using typedoc

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy-docs:
    uses: ./.github/workflows/deploy-typedoc.yml
    with:
      build-dependencies: '@arcmantle/tsconfig'
    permissions:
      contents: read
      pages: write
      id-token: write
