name: Publish Package

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  publish:
    uses: arcmantle/github-workflows/.github/workflows/pnpm-publish.yml@main
    secrets:
      NPM_PUBLISH: ${{ secrets.NPM_PUBLISH }}
