<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net9.0</TargetFramework>
		<ImplicitUsings>disable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<EnableDefaultCompileItems>false</EnableDefaultCompileItems>
		<NoWarn>CS8321</NoWarn>
	</PropertyGroup>
	<ItemGroup>
		<Compile Include="scripts\**\*.cs" />
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="cache\_helpers\helpers_cs\ForgeHelpers.csproj" />
	</ItemGroup>
</Project>
