using System;
using System.Collections.Generic;
using System.Linq;

namespace Changelog;

/// <summary>
/// Computes efficient diffs for arrays/lists using Longest Common Subsequence (LCS) algorithm.
/// Instead of storing entire arrays, generates granular add/remove/modify operations.
/// </summary>
public static class ArrayDiffer {
	/// <summary>
	/// Compute minimal diff between two arrays using LCS algorithm.
	/// Returns a sequence of operations to transform oldArray into newArray.
	/// </summary>
	public static List<ArrayChange> Diff<T>(IEnumerable<T>? oldArray, IEnumerable<T>? newArray) {
		var oldList = oldArray?.ToList() ?? new List<T>();
		var newList = newArray?.ToList() ?? new List<T>();

		if (oldList.Count == 0 && newList.Count == 0) {
			return new List<ArrayChange>();
		}

		// Compute LCS using dynamic programming
		var lcs = ComputeLCS(oldList, newList);

		// Generate diff operations from LCS
		return GenerateChanges(oldList, newList, lcs);
	}

	/// <summary>
	/// Compute LCS lengths using dynamic programming.
	/// Returns DP table where dp[i,j] = length of LCS of oldList[0..i-1] and newList[0..j-1].
	/// </summary>
	private static int[,] ComputeLCS<T>(List<T> oldList, List<T> newList) {
		int m = oldList.Count;
		int n = newList.Count;
		var dp = new int[m + 1, n + 1];

		// Build DP table bottom-up
		for (int i = 1; i <= m; i++) {
			for (int j = 1; j <= n; j++) {
				if (EqualityComparer<T>.Default.Equals(oldList[i - 1], newList[j - 1])) {
					dp[i, j] = dp[i - 1, j - 1] + 1;
				}
				else {
					dp[i, j] = Math.Max(dp[i - 1, j], dp[i, j - 1]);
				}
			}
		}

		return dp;
	}

	/// <summary>
	/// Generate array change operations by backtracking through LCS table.
	/// </summary>
	private static List<ArrayChange> GenerateChanges<T>(List<T> oldList, List<T> newList, int[,] lcs) {
		var changes = new List<ArrayChange>();
		int i = oldList.Count;
		int j = newList.Count;

		// Backtrack through LCS table to find differences
		while (i > 0 || j > 0) {
			if (i > 0 && j > 0 && EqualityComparer<T>.Default.Equals(oldList[i - 1], newList[j - 1])) {
				// Items match - part of LCS, no change needed
				i--;
				j--;
			}
			else if (j > 0 && (i == 0 || lcs[i, j - 1] >= lcs[i - 1, j])) {
				// Item added in new array
				changes.Add(new ArrayChange {
					Type = ArrayChangeType.Add,
					Index = j - 1,
					NewValue = newList[j - 1]
				});
				j--;
			}
			else if (i > 0) {
				// Item removed from old array
				changes.Add(new ArrayChange {
					Type = ArrayChangeType.Remove,
					Index = i - 1,
					OldValue = oldList[i - 1]
				});
				i--;
			}
		}

		// Changes were found in reverse order, so reverse them
		changes.Reverse();

		// Post-process to detect modifications (remove + add at same index)
		return OptimizeChanges(changes);
	}

	/// <summary>
	/// Optimize changes by converting adjacent Remove+Add at same index into Modify.
	/// </summary>
	private static List<ArrayChange> OptimizeChanges(List<ArrayChange> changes) {
		var optimized = new List<ArrayChange>();

		for (int i = 0; i < changes.Count; i++) {
			var current = changes[i];

			// Look for Remove followed by Add at same logical position
			if (i < changes.Count - 1 &&
				 current.Type == ArrayChangeType.Remove &&
				 changes[i + 1].Type == ArrayChangeType.Add &&
				 current.Index == changes[i + 1].Index) {
				// Combine into Modify
				optimized.Add(new ArrayChange {
					Type = ArrayChangeType.Modify,
					Index = current.Index,
					OldValue = current.OldValue,
					NewValue = changes[i + 1].NewValue
				});
				i++; // Skip the Add since we merged it
			}
			else {
				optimized.Add(current);
			}
		}

		return optimized;
	}

	/// <summary>
	/// Apply array changes to reconstruct the new array state.
	/// Useful for verifying diffs or applying changes.
	/// NOTE: Assumes changes are in the order generated by Diff() method.
	/// </summary>
	public static List<T> ApplyChanges<T>(IEnumerable<T>? oldArray, IEnumerable<ArrayChange> changes) {
		var result = oldArray?.ToList() ?? new List<T>();

		// Separate removes and other operations
		// Removes need to be applied in reverse index order to avoid shifting issues
		var changesList = changes.ToList();
		var removes = changesList.Where(c => c.Type == ArrayChangeType.Remove).OrderByDescending(c => c.Index).ToList();
		var others = changesList.Where(c => c.Type != ArrayChangeType.Remove).ToList();

		// Apply removes first (in reverse index order)
		foreach (var change in removes) {
			if (change.Index >= 0 && change.Index < result.Count) {
				result.RemoveAt(change.Index);
			}
		}

		// Then apply adds and modifies
		foreach (var change in others) {
			switch (change.Type) {
			case ArrayChangeType.Add:
				if (change.NewValue is T newValue) {
					// Insert at index (or append if out of bounds)
					if (change.Index <= result.Count) {
						result.Insert(change.Index, newValue);
					}
					else {
						result.Add(newValue);
					}
				}
				break;

			case ArrayChangeType.Modify:
				if (change.NewValue is T modifiedValue &&
						change.Index >= 0 && change.Index < result.Count) {
					result[change.Index] = modifiedValue;
				}
				break;
			}
		}

		return result;
	}
}

/// <summary>
/// Represents a single change operation on an array.
/// </summary>
public record ArrayChange {
	/// <summary>
	/// Type of change (Add, Remove, or Modify).
	/// </summary>
	public required ArrayChangeType Type { get; init; }

	/// <summary>
	/// Zero-based index where the change occurred.
	/// </summary>
	public required int Index { get; init; }

	/// <summary>
	/// The old value (for Remove and Modify operations).
	/// </summary>
	public object? OldValue { get; init; }

	/// <summary>
	/// The new value (for Add and Modify operations).
	/// </summary>
	public object? NewValue { get; init; }
}

/// <summary>
/// Type of array change operation.
/// </summary>
public enum ArrayChangeType {
	/// <summary>
	/// An item was added to the array.
	/// </summary>
	Add,

	/// <summary>
	/// An item was removed from the array.
	/// </summary>
	Remove,

	/// <summary>
	/// An item was modified (value changed at same index).
	/// </summary>
	Modify
}
