pnpmfile: ../.pnpmfile.cjs

packages:
  - "*"
  - "**"

catalogs:
  experimental:
    '@preact/signals-core': ^1.11.0
    '@types/node': ^25.0.3
    '@webgpu/types': ^0.1.60
    lit: ^3.3.0
    solid-js: ^1.9.5
    tslib: ^2.8.1
    typedoc: ^0.28.15
    typedoc-github-theme: ^0.3.0
    typescript: ^5.9.2
    vite: ^7.3.0
    vite-plugin-solid: ^2.11.6
    vitest: ^4.0.16
