packages:
  - '*'
  - '**'

allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  rs-module-lexer: true

catalogs:
  ui-components:
    '@arcmantle/adapter-element': ^1.0.0
    '@arcmantle/library': ^1.0.0
    '@arcmantle/lit-jsx': ^1.0.0
    '@arcmantle/mirage-mde-display': ^1.0.0
    '@arcmantle/vite-plugin-import-css-sheet': ^1.0.1
    '@codemirror/autocomplete': ^6.18.6
    '@codemirror/commands': ^6.8.1
    '@codemirror/lang-markdown': ^6.3.2
    '@codemirror/language': ^6.11.0
    '@codemirror/language-data': ^6.5.1
    '@codemirror/lint': ^6.8.5
    '@codemirror/search': ^6.5.10
    '@codemirror/state': ^6.5.2
    '@codemirror/view': ^6.36.5
    '@faker-js/faker': ^9.7.0
    '@floating-ui/dom': ^1.6.13
    '@lezer/highlight': ^1.2.1
    '@lezer/markdown': ^1.4.2
    '@microsoft/api-extractor': ^7.52.3
    '@types/node': ^25.0.3
    cm6-theme-basic-dark: ^0.2.0
    highlight.js: ^11.11.1
    lit: ^3.3.0
    lit-html: ^3.3.1
    marked: ^16.0.0
    marked-extended-tables: ^2.0.1
    marked-gfm-heading-id: ^4.1.1
    marked-highlight: ^2.2.1
    marked-mangle: ^1.1.10
    monaco-editor: ^0.52.2
    rimraf: ^6.0.1
    tslib: ^2.8.1
    typedoc: ^0.28.15
    typedoc-github-theme: ^0.3.0
    typescript: ^5.9.2
    vite: ^7.3.0
    vitest: ^4.0.16

onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - rs-module-lexer

pnpmfile: ../.pnpmfile.cjs
