name: Sync posix-path-browser to standalone repo

on:
  push:
    branches: [main]
    paths: ['packages/core/posix-path-browser/**']
  workflow_dispatch:

jobs:
  sync-subtree:
    uses: arcmantle/github-workflows/.github/workflows/subtree-sync.yml@main
    with:
      package-path: packages/core/posix-path-browser
      target-repo: arcmantle/posix-path-browser
    secrets:
      sync-token: ${{ secrets.SYNC_SUBTREE }}
