name: Sync lit-jsx to standalone repo

on:
  push:
    branches: [main]
    paths: ['packages/lit-jsx/**']
  workflow_dispatch:

jobs:
  sync-subtree:
    uses: arcmantle/subtree-sync.yml@main
    with:
      package-path: packages/lit-jsx
      target-repo: arcmantle/jsx-lit
    secrets:
      sync-token: ${{ secrets.SYNC_SUBTREE }}
